name: Compile JOSS pdf
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Compile pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build draft pdf
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md
      - name: Upload built pdf
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: paper/paper.pdf
