name: Compile JOSS .tex
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Compile paper
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TeX
        uses: docker://openjournals/paperdraft:latest
        with:
          args: paper/paper.md --to=latex --output=paper.tex
        env:
          GIT_SHA: $GITHUB_SHA
          JOURNAL: joss
      - name: PDF
        uses: docker://openjournals/paperdraft:latest
        with:
          args: paper/paper.md
        env:
          GIT_SHA: $GITHUB_SHA
          JOURNAL: joss
      - uses: actions/upload-artifact@v2
        with:
          path: paper
